[package]
name = "cloaker"
version = "4.0.0"
authors = ["Theron Spiegl <tspiegl@gmail.com>"]
edition = "2018"

[dependencies]
argon2 = "0.3.1"
scrypt = "0.8.0"
crypto_secretstream = "0.0.1"
rand_core = { version = "0.6", features = ["std"] }
