[package]
name = "adapter"
version = "4.0.0"
authors = ["Theron Spiegl <tspiegl@gmail.com>"]
edition = "2018"

[lib]
name = "adapter"
crate-type = ["staticlib"]

[dependencies]
cloaker = { path = "../core" }
